# Generated by Django 6.0.2 on 2026-05-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0002_valores_comprovante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valores',
            name='comprovante',
        ),
    ]
