# Generated by Django 6.0.2 on 2026-02-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta_rename_cateforia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='banco',
            field=models.CharField(choices=[('PS', 'Pessoal'), ('TR', 'Trabalho'), ('FM', 'Família'), ('EC', 'Economia'), ('IV', 'Investimentos'), ('EM', 'Emergência'), ('LZ', 'Lazer'), ('ED', 'Educação')], max_length=2),
        ),
        migrations.AlterField(
            model_name='conta',
            name='tipo',
            field=models.CharField(choices=[('pf', 'Individual'), ('pj', 'Compartilhado')], max_length=2),
        ),
    ]
