# Generated by Django 6.0.2 on 2026-05-08 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_notificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totpdevice',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
        migrations.DeleteModel(
            name='TOTPDevice',
        ),
    ]
