# Generated by Django 6.0.2 on 2026-02-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfil', '0002_conta_rename_cateforia_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('economia_mensal', 'Economizar por mês'), ('limite_categoria', 'Limite de gasto por categoria')], max_length=20)),
                ('valor', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.categoria')),
            ],
        ),
    ]
