# Generated by Django 6.0.2 on 2026-02-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
