# Generated by Django 6.0.2 on 2026-02-19 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_contapagar_recorrente'),
        ('perfil', '0003_alter_conta_banco_alter_conta_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapaga',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='contapaga',
            name='conta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perfil.conta'),
        ),
        migrations.AddField(
            model_name='contapaga',
            name='metodo_pagamento',
            field=models.CharField(choices=[('boleto', 'Boleto Bancário'), ('pix', 'PIX'), ('debito', 'Débito Automático'), ('transferencia', 'Transferência')], default='boleto', max_length=20),
        ),
        migrations.AddField(
            model_name='contapaga',
            name='nosso_numero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contapaga',
            name='valor_pago',
            field=models.FloatField(default=0),
        ),
    ]
