# Generated by Django 6.0.2 on 2026-02-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('summary', models.CharField(max_length=300, verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagem')),
                ('category', models.CharField(choices=[('planejamento', 'Planejamento Financeiro'), ('investimentos', 'Investimentos'), ('economia', 'Economia'), ('dicas', 'Dicas'), ('noticias', 'Notícias'), ('mercado', 'Mercado')], default='noticias', max_length=30, verbose_name='Categoria')),
                ('published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
